train:
  gpu_id: [0]
  num: 16
  prefix: /data/experiment_data/polygon-rnn/checkpoint/train1
  log_dir: /data/experiment_data/polygon-rnn/runs/train1
  batch_size: 32
  lr: 0.001

#  pretrained:

val:
  gpu_id: [0]
  num: 10
  model: /data/experiment_data/polygon-rnn/save/model_45000.pth
  batch_size: 32
  dataset: val

test:
  gpu_id: [0]
  num: 10
  model: /data/experiment_data/polygon-rnn/save/model_45000.pth
  dataset: val
